python3.8: can't open file 'HoshinoBot/run.py': [Errno 2] No such file or directory
python3.8: can't open file 'HoshinoBot/run.py': [Errno 2] No such file or directory
